title: Charles O'Farrell
email: charleso@charleso.org
baseurl: ""
url: "https://blog.charleso.org"
twitter_username: charlesofarrell
github_username:  charleso
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - blog.md
  - talks.md
  - software.md
  - teaching.md
  - resume/index.md
